# Generated by Django 4.2.3 on 2023-07-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('quote', models.CharField(max_length=4500)),
                ('years', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=5000)),
            ],
        ),
    ]
